lessons/lesson.37/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls')),
]

lessons/lesson.37/sales_shop/site_auth/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import LoginView, LogoutView, RegisterView

app_name = "site_auth"

urlpatterns = [
    path(
        "me/",
        TemplateView.as_view(template_name="site_auth/me.html"),
        name="about-me",
     ),
    path(
        "login/",
        # TemplateView.as_view(template_name="site_auth/login.html"),
        LoginView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "register/",
        RegisterView.as_view(),
        name="register",
    ),
]

lessons/lesson.37/zoo/urls.py
from django.contrib import admin
from django.urls import path, include
from animals.views import animals_list_view
from contacts.views import contact_view, status_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', animals_list_view),
    path('contacts/', contact_view),
    path('status/<str:task_id>/', status_view),
    path("__debug__/", include("debug_toolbar.urls")),
]

lessons/lesson.37/zoo/zoo/urls.py
from django.contrib import admin
from django.urls import path, include

import main.views as main

urlpatterns = [
    path('', include('main.urls', namespace='animals')),
    path('auth/', include('myauth.urls', namespace='myauth')),
    path('send/', main.send_mail),
    path('status/<str:task_id>/', main.task_status),
    path('admin/', admin.site.urls),
]

lessons/lesson.37/sales_shop/site_auth/forms.py
from django.contrib.auth.forms import (
    AuthenticationForm as AuthenticationFormGeneric,
    UserCreationForm as UserCreationFormGeneric,
)
from django import forms


class AuthenticationForm(AuthenticationFormGeneric):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field: forms.Field
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"


class UserCreationForm(UserCreationFormGeneric):
    class Meta(UserCreationFormGeneric.Meta):
        fields = "username", "email",

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field: forms.Field
            widget: forms.Widget = field.widget
            widget.attrs["class"] = "form-control"

lessons/lesson.37/sales_shop/site_auth/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.views import (
    LoginView as LoginViewGeneric,
    LogoutView as LogoutViewGeneric,
)
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import AuthenticationForm, UserCreationForm
from .tasks import welcome_user


class LoginView(LoginViewGeneric):
    template_name = "site_auth/login.html"
    form_class = AuthenticationForm
    next_page = reverse_lazy("site_auth:about-me")


class LogoutView(LogoutViewGeneric):
    next_page = reverse_lazy("site_auth:about-me")


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "site_auth/register.html"
    success_url = reverse_lazy("site_auth:about-me")

    def form_valid(self, form):
        response = super().form_valid(form)
        welcome_user.delay(self.object.pk)
        # user: AbstractUser = self.object
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user: AbstractUser = authenticate(
            self.request,
            username=username,
            password=password,
        )
        login(request=self.request, user=user)
        return response

lessons/lesson.37/sales_shop/site_auth/templates/site_auth/login.html
{% extends 'base.html' %}

{% block title %}
  Login to Site
{% endblock %}

{% block body %}
  <!-- Pills content -->
  <form method="post">
    {% csrf_token %}

    {% if form.errors %}
      <p class="alert alert-danger">
        Something is not right
      </p>
    {% endif %}

    {{ form.as_p }}

    <input type="hidden" name="next" value="{{ next }}">

    <!-- Submit button -->
    <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

    <!-- Register buttons -->
    <div class="text-center">
      <p>Not a member? <a href="{% url 'site_auth:register' %}">Register</a></p>
    </div>
  </form>
  <!-- Pills content -->
{% endblock %}

lessons/lesson.37/sales_shop/site_auth/templates/site_auth/me.html
{% extends 'base.html' %}

{% block title %}
  About Me
{% endblock %}

{% block body %}
  <h1>User info</h1>
  {% if user.is_authenticated %}
    <p>Username: {{ user.username }}</p>
    <p>email: {{ user.email }}</p>
  {% else %}
    <h2>Anonymous user</h2>
  {% endif %}
{% endblock %}

lessons/lesson.37/sales_shop/site_auth/templates/site_auth/register.html
{% extends 'base.html' %}

{% block title %}
  Register
{% endblock %}

{% block body %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Register">
  </form>
{% endblock %}